name = "av-ingest"
main = "worker/worker.js"
compatibility_date = "2026-05-10"
account_id = "c57bb20727aa3564966d2bb693abddce"

routes = [
  { pattern = "wavey.ai/code/av-ingest*", zone_name = "wavey.ai" },
  { pattern = "www.wavey.ai/code/av-ingest*", zone_name = "wavey.ai" },
]

[assets]
directory = "./public"
binding = "ASSETS"
not_found_handling = "single-page-application"
